/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANDHIKA WAHYU K
 */

//memanggil library/api yang diperlukan
import koneksi.koneksiDB;
import java.sql.*;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmkategori extends javax.swing.JFrame {
    

    //membuat objek    
    private DefaultTableModel model;
    
    //deklarasi variabel
    String kdkategori, kdkode, kd_stock;
    
  
    public frmkategori() {
        initComponents();
        
        //membuat obyek
        model = new DefaultTableModel();
        
        //memberi nama header pada tabel
        tblkategori.setModel(model);
        model.addColumn("KATEGORI BARANG");
        model.addColumn("HARGA SATUAN");
        model.addColumn("JUMLAH STOCK");
        
        getDatakategori();
    }

     //fungsi membaca data kategori
    public void getDatakategori(){
        //kosongkan tabel
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        //eksekusi koneksi dan kirimkan query ke database
        try{
            //tes koneksi
            Statement stat = (Statement) koneksiDB.getKoneksi().createStatement();
            
            //perintah sql untuk membaca data dari tabel kategori        
            String sql = "SELECT * FROM tbl_kategori";
            ResultSet res = stat.executeQuery(sql);
            
            //baca data
            while(res.next()){
                //membuat obyek berjenis array
                Object[] obj = new Object[3];
                obj[0]=res.getString("kd_kategori");
                obj[1]=res.getString("kd_kode");
                obj[2]=res.getString("stock");
                model.addRow(obj);
            }
          }catch(SQLException err){
           JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtkategori = new javax.swing.JTextField();
        tmblsimpan = new javax.swing.JButton();
        tmblubah = new javax.swing.JButton();
        tmblkembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkategori = new javax.swing.JTable();
        tmblreset = new javax.swing.JButton();
        txtkode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("KATEGORI");

        jLabel2.setText("KATEGORI BARANG :");

        jLabel3.setText("HARGA SATUAN       :");

        txtkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkategoriActionPerformed(evt);
            }
        });

        tmblsimpan.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        tmblsimpan.setText("SIMPAN");
        tmblsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblsimpanActionPerformed(evt);
            }
        });

        tmblubah.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        tmblubah.setText("UBAH");
        tmblubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblubahActionPerformed(evt);
            }
        });

        tmblkembali.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        tmblkembali.setText("KEMBALI");
        tmblkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmblkembaliMouseClicked(evt);
            }
        });
        tmblkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblkembaliActionPerformed(evt);
            }
        });

        tblkategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblkategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkategori);

        tmblreset.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        tmblreset.setText("RESET");
        tmblreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblresetActionPerformed(evt);
            }
        });

        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });

        jLabel4.setText("JUMLAH STOCK        :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtkategori)
                                            .addComponent(txtkode, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtstock)
                                        .addGap(1, 1, 1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tmblsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tmblubah)
                                .addGap(18, 18, 18)
                                .addComponent(tmblreset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tmblkembali))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmblsimpan)
                    .addComponent(tmblubah)
                    .addComponent(tmblreset)
                    .addComponent(tmblkembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//membaca data 
    public void loadDatakategori(){
        kdkategori = txtkategori.getText();
        kdkode = txtkode.getText();
        kd_stock = txtstock.getText();
    }
    
    public void dataSelect(){
        //deklarasi variabel
        int i = tblkategori.getSelectedRow();
        
        //uji adakah data di tabel?
        if(i == -1){
            //tidak ada yang terpilih atau dipilih.
            return;
        }
        txtkategori.setText(""+model.getValueAt(i,0));
        txtkode.setText(""+model.getValueAt(i,1));
        txtstock.setText(""+model.getValueAt(i,2));
    }
    
    public void reset(){
        kdkategori = "";
        kdkode = "";
        kd_stock = "";
               
        txtkategori.setText(kdkategori);
        txtkode.setText(kdkode);
        txtstock.setText(kd_stock);
    }
 
     public void simpanDatakategori(){
         
        loadDatakategori();
        try{
            
            Statement stat = (Statement) koneksiDB.getKoneksi().createStatement();
            
            
            String  sql =   "INSERT INTO tbl_kategori(kd_kategori, kd_kode, stock)" + "VALUES('"+ kdkategori +"','"+ kdkode +"','"+ kd_stock +"')";
            PreparedStatement p = (PreparedStatement) koneksiDB.getKoneksi().prepareStatement(sql);
            p.executeUpdate();  
            
            getDatakategori();
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    
    public void ubahDatakategori(){
        //fungsi load data kategori
        loadDatakategori();
        
        try{
            //uji koneksi
            Statement stat = (Statement) koneksiDB.getKoneksi().createStatement();
            
            //kirim perintah sql
            String sql = "UPDATE tbl_kategori SET kd_kode = '"+ kdkode +"',"
                    + "stock  = '"+ kd_stock +"'"
                    + "WHERE kd_kategori = '"+ kdkategori +"'";
            PreparedStatement p =(PreparedStatement)koneksiDB.getKoneksi().prepareStatement(sql); 
            p.executeUpdate();
            
            getDatakategori();
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    
    public void hapusDatakategori(){
        
        loadDatakategori(); 
      
        int pesan = JOptionPane.showConfirmDialog(null, "HAPUS DATA "+ kdkategori +"?","YAKIN", JOptionPane.OK_CANCEL_OPTION);
       
        if(pesan == JOptionPane.OK_OPTION){
            try{
                Statement stat = (Statement) koneksiDB.getKoneksi().createStatement();
                
                
                String sql = "DELETE FROM tbl_kategori WHERE kd_kategori='"+ kdkategori +"'";
                PreparedStatement p =(PreparedStatement)koneksiDB.getKoneksi().prepareStatement(sql);
                p.executeUpdate();
                
                
                getDatakategori();
                
                reset();
                JOptionPane.showMessageDialog(null, "BERHASIL DIHAPUS!!!");
            }catch(SQLException err){
                JOptionPane.showMessageDialog(null, err.getMessage());
            }
        }
    }
    private void txtkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkategoriActionPerformed

    private void tmblkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblkembaliActionPerformed
        new frmutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmblkembaliActionPerformed

    private void tmblkembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmblkembaliMouseClicked
        new frmutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tmblkembaliMouseClicked

    private void tmblsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblsimpanActionPerformed
        simpanDatakategori();
    }//GEN-LAST:event_tmblsimpanActionPerformed

    private void tmblubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblubahActionPerformed
        ubahDatakategori();
    }//GEN-LAST:event_tmblubahActionPerformed

    private void tmblresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblresetActionPerformed
        hapusDatakategori();
    }//GEN-LAST:event_tmblresetActionPerformed

    private void tblkategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkategoriMouseClicked
        dataSelect();
    }//GEN-LAST:event_tblkategoriMouseClicked

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmkategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmkategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmkategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmkategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmkategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblkategori;
    private javax.swing.JButton tmblkembali;
    private javax.swing.JButton tmblreset;
    private javax.swing.JButton tmblsimpan;
    private javax.swing.JButton tmblubah;
    private javax.swing.JTextField txtkategori;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables
}
